// Copyright 2016 The go-ethereum Authors
// This file is part of go-ethereum.
//
// go-ethereum is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// go-ethereum is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with go-ethereum. If not, see <http://www.gnu.org/licenses/>.

package main

import (
	"encoding/hex"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"regexp"
	"runtime"
	"strings"

	"github.com/donutnomad/eths/abi/abigen"
	"github.com/donutnomad/eths/abi/compiler"
	"github.com/donutnomad/eths/abi/gogenapi"
	"golang.org/x/crypto/sha3"
)

// EncodeHex encodes b as a hex string with 0x prefix.
func EncodeHex(b []byte) string {
	enc := make([]byte, len(b)*2+2)
	copy(enc, "0x")
	hex.Encode(enc[2:], b)
	return string(enc)
}

// Keccak256Hash calculates and returns the Keccak256 hash of the input data,
// converting it to an internal Hash data structure.
func Keccak256Hash(data ...[]byte) (h [32]byte) {
	d := sha3.NewLegacyKeccak256()
	d.Reset()
	for _, b := range data {
		d.Write(b)
	}
	d.(io.Reader).Read(h[:])
	return h
}

var (
	abiFlagName   = "abi"
	binFlagName   = "bin"
	typeFlagName  = "type"
	jsonFlagName  = "combined-json"
	excFlagName   = "exc"
	pkgFlagName   = "pkg"
	outFlagName   = "out"
	aliasFlagName = "alias"
	v2FlagName    = "v2"
)

var app = newAbigenApp()

type abigenApp struct{}

type abigenConfig struct {
	abi          string
	bin          string
	kind         string
	combinedJSON string
	exc          string
	pkg          string
	out          string
	alias        string
	v2           bool
	set          map[string]bool
}

func newAbigenApp() *abigenApp {
	return &abigenApp{}
}

func (app *abigenApp) Run(args []string) error {
	cfg, err := parseAbigenArgs(args)
	if err != nil {
		if errors.Is(err, flag.ErrHelp) {
			return nil
		}
		return err
	}
	return generate(cfg)
}

func parseAbigenArgs(args []string) (abigenConfig, error) {
	cfg := abigenConfig{set: make(map[string]bool)}
	flags := flag.NewFlagSet("abigen", flag.ContinueOnError)
	flags.StringVar(&cfg.abi, abiFlagName, "", "Path to the Ethereum contract ABI json to bind, @artifact.json for artifact ABI and bytecode, - for STDIN")
	flags.StringVar(&cfg.bin, binFlagName, "", "Path to the Ethereum contract bytecode (generate deploy method)")
	flags.StringVar(&cfg.kind, typeFlagName, "", "Struct name for the binding (default = package name)")
	flags.StringVar(&cfg.combinedJSON, jsonFlagName, "", "Path to the combined-json file generated by compiler, - for STDIN")
	flags.StringVar(&cfg.exc, excFlagName, "", "Comma separated types to exclude from binding")
	flags.StringVar(&cfg.pkg, pkgFlagName, "", "Package name to generate the binding into")
	flags.StringVar(&cfg.out, outFlagName, "", "Output file for the generated binding (default = stdout)")
	flags.StringVar(&cfg.alias, aliasFlagName, "", "Comma separated aliases for function and event renaming. If --v2 is set, errors are aliased as well. e.g. original1=alias1, original2=alias2")
	flags.BoolVar(&cfg.v2, v2FlagName, false, "Generates v2 bindings")

	if len(args) > 0 {
		args = args[1:]
	}
	if err := flags.Parse(args); err != nil {
		return cfg, err
	}
	flags.Visit(func(f *flag.Flag) {
		cfg.set[f.Name] = true
	})
	return cfg, nil
}

func (c abigenConfig) isSet(name string) bool {
	return c.set[name]
}

type abiInput struct {
	ABI []byte
	Bin []byte
}

// Fatalf formats a message to standard error and exits the program.
// The message is also printed to standard output if standard error
// is redirected to a different file.
func Fatalf(format string, args ...interface{}) {
	w := io.MultiWriter(os.Stdout, os.Stderr)
	if runtime.GOOS == "windows" || runtime.GOOS == "openbsd" {
		// The SameFile check below doesn't work on Windows neither OpenBSD.
		// stdout is unlikely to get redirected though, so just print there.
		w = os.Stdout
	} else {
		outf, _ := os.Stdout.Stat()
		errf, _ := os.Stderr.Stat()
		if outf != nil && errf != nil && os.SameFile(outf, errf) {
			w = os.Stderr
		}
	}
	fmt.Fprintf(w, "Fatal: "+format+"\n", args...)
	os.Exit(1)
}

func readABIInput(input string, stdin io.Reader) (abiInput, error) {
	if input == "-" {
		abi, err := io.ReadAll(stdin)
		if err != nil {
			return abiInput{}, err
		}
		return abiInput{ABI: abi}, nil
	}
	if strings.HasPrefix(input, "@") {
		artifact, err := gogenapi.LoadInput(input)
		if err != nil {
			return abiInput{}, err
		}
		return abiInput{ABI: artifact.ABI, Bin: artifact.Bytecode}, nil
	}
	abi, err := os.ReadFile(input)
	if err != nil {
		return abiInput{}, err
	}
	return abiInput{ABI: abi}, nil
}

func generate(c abigenConfig) error {
	if err := checkExclusive(c, abiFlagName, jsonFlagName); err != nil {
		return err
	}

	if c.pkg == "" {
		Fatalf("No destination package specified (--pkg)")
	}
	if c.abi == "" && c.combinedJSON == "" {
		Fatalf("Either contract ABI source (--abi) or combined-json (--combined-json) are required")
	}
	// If the entire solidity code was specified, build and bind based on that
	var (
		abis    []string
		bins    []string
		types   []string
		sigs    []map[string]string
		libs    = make(map[string]string)
		aliases = make(map[string]string)
	)
	if c.abi != "" {
		// Load up the ABI, optional bytecode and type name from the parameters
		input := c.abi
		abiInput, err := readABIInput(input, os.Stdin)
		if err != nil {
			Fatalf("Failed to read input ABI: %v", err)
		}
		abis = append(abis, string(abiInput.ABI))

		bin := abiInput.Bin
		if binFile := c.bin; binFile != "" {
			if bin, err = os.ReadFile(binFile); err != nil {
				Fatalf("Failed to read input bytecode: %v", err)
			}
		}
		if strings.Contains(string(bin), "//") {
			Fatalf("Contract has additional library references, please use other mode(e.g. --combined-json) to catch library infos")
		}
		bins = append(bins, string(bin))

		kind := c.kind
		if kind == "" {
			kind = c.pkg
		}
		types = append(types, kind)
	} else {
		// Generate the list of types to exclude from binding
		var exclude *nameFilter
		if c.isSet(excFlagName) {
			var err error
			if exclude, err = newNameFilter(strings.Split(c.exc, ",")...); err != nil {
				Fatalf("Failed to parse excludes: %v", err)
			}
		}
		var contracts map[string]*compiler.Contract

		if c.isSet(jsonFlagName) {
			var (
				input      = c.combinedJSON
				jsonOutput []byte
				err        error
			)
			if input == "-" {
				jsonOutput, err = io.ReadAll(os.Stdin)
			} else {
				jsonOutput, err = os.ReadFile(input)
			}
			if err != nil {
				Fatalf("Failed to read combined-json: %v", err)
			}
			contracts, err = compiler.ParseCombinedJSON(jsonOutput, "", "", "", "")
			if err != nil {
				Fatalf("Failed to read contract information from json output: %v", err)
			}
		}
		// Gather all non-excluded contract for binding
		for name, contract := range contracts {
			// fully qualified name is of the form <solFilePath>:<type>
			nameParts := strings.Split(name, ":")
			typeName := nameParts[len(nameParts)-1]
			if exclude != nil && exclude.Matches(name) {
				fmt.Fprintf(os.Stderr, "excluding: %v\n", name)
				continue
			}
			abi, err := json.Marshal(contract.Info.AbiDefinition) // Flatten the compiler parse
			if err != nil {
				Fatalf("Failed to parse ABIs from compiler output: %v", err)
			}
			abis = append(abis, string(abi))
			bins = append(bins, contract.Code)
			sigs = append(sigs, contract.Hashes)
			types = append(types, typeName)

			// Derive the library placeholder which is a 34 character prefix of the
			// hex encoding of the keccak256 hash of the fully qualified library name.
			// Note that the fully qualified library name is the path of its source
			// file and the library name separated by ":".
			tmp := Keccak256Hash([]byte(name))
			libPattern := EncodeHex(tmp[:])[2:36] // the first 2 chars are 0x
			libs[libPattern] = typeName
		}
	}
	// Extract all aliases from the flags
	if c.isSet(aliasFlagName) {
		// We support multi-versions for aliasing
		// e.g.
		//      foo=bar,foo2=bar2
		//      foo:bar,foo2:bar2
		re := regexp.MustCompile(`(?:(\w+)[:=](\w+))`)
		submatches := re.FindAllStringSubmatch(c.alias, -1)
		for _, match := range submatches {
			aliases[match[1]] = match[2]
		}
	}
	// Generate the contract binding
	var (
		code string
		err  error
	)
	if c.v2 {
		code, err = abigen.BindV2(types, abis, bins, c.pkg, libs, aliases)
	} else {
		code, err = abigen.Bind(types, abis, bins, sigs, c.pkg, libs, aliases)
	}
	if err != nil {
		Fatalf("Failed to generate ABI binding: %v", err)
	}
	// Either flush it out to a file or display on the standard output
	if !c.isSet(outFlagName) {
		fmt.Printf("%s\n", code)
		return nil
	}
	if err := os.WriteFile(c.out, []byte(code), 0600); err != nil {
		Fatalf("Failed to write ABI binding: %v", err)
	}
	return nil
}

func checkExclusive(c abigenConfig, names ...string) error {
	set := make([]string, 0, 1)
	for _, name := range names {
		if c.isSet(name) {
			set = append(set, "--"+name)
		}
	}
	if len(set) > 1 {
		return fmt.Errorf("flags %s are mutually exclusive", strings.Join(set, ", "))
	}
	return nil
}

func main() {
	if err := app.Run(os.Args); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
