// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package ethtype

import (
	"encoding/json"

	"github.com/donutnomad/eths/ecommon"
)

// MarshalJSON marshals as JSON.
func (a AccessTuple) MarshalJSON() ([]byte, error) {
	type AccessTuple struct {
		Address     ecommon.Address `json:"address"`
		StorageKeys []ecommon.Hash  `json:"storageKeys"`
	}
	var enc AccessTuple
	enc.Address = a.Address
	enc.StorageKeys = a.StorageKeys
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (a *AccessTuple) UnmarshalJSON(input []byte) error {
	type AccessTuple struct {
		Address     *ecommon.Address `json:"address"`
		StorageKeys []ecommon.Hash   `json:"storageKeys"`
	}
	var dec AccessTuple
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.Address != nil {
		a.Address = *dec.Address
	}
	if dec.StorageKeys != nil {
		a.StorageKeys = dec.StorageKeys
	}
	return nil
}
