// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package ethtype

import (
	"encoding/json"

	"github.com/donutnomad/eths/ecommon"
	"github.com/ethereum/go-ethereum/common/hexutil"
	"github.com/holiman/uint256"
)

var _ = (*authorizationMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (s SetCodeAuthorization) MarshalJSON() ([]byte, error) {
	type SetCodeAuthorization struct {
		ChainID hexutil.U256    `json:"chainId"`
		Address ecommon.Address `json:"address"`
		Nonce   hexutil.Uint64  `json:"nonce"`
		V       hexutil.Uint64  `json:"yParity"`
		R       hexutil.U256    `json:"r"`
		S       hexutil.U256    `json:"s"`
	}
	var enc SetCodeAuthorization
	enc.ChainID = hexutil.U256(s.ChainID)
	enc.Address = s.Address
	enc.Nonce = hexutil.Uint64(s.Nonce)
	enc.V = hexutil.Uint64(s.V)
	enc.R = hexutil.U256(s.R)
	enc.S = hexutil.U256(s.S)
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (s *SetCodeAuthorization) UnmarshalJSON(input []byte) error {
	type SetCodeAuthorization struct {
		ChainID *hexutil.U256    `json:"chainId"`
		Address *ecommon.Address `json:"address"`
		Nonce   *hexutil.Uint64  `json:"nonce"`
		V       *hexutil.Uint64  `json:"yParity"`
		R       *hexutil.U256    `json:"r"`
		S       *hexutil.U256    `json:"s"`
	}
	var dec SetCodeAuthorization
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.ChainID != nil {
		s.ChainID = uint256.Int(*dec.ChainID)
	}
	if dec.Address != nil {
		s.Address = *dec.Address
	}
	if dec.Nonce != nil {
		s.Nonce = uint64(*dec.Nonce)
	}
	if dec.V != nil {
		s.V = uint8(*dec.V)
	}
	if dec.R != nil {
		s.R = uint256.Int(*dec.R)
	}
	if dec.S != nil {
		s.S = uint256.Int(*dec.S)
	}
	return nil
}
