// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package ethtype

import (
	"encoding/json"
	"math/big"

	"github.com/donutnomad/eths/ecommon"
	"github.com/donutnomad/eths/hexutil"
)

var _ = (*headerMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (l LiteBlock) MarshalJSON() ([]byte, error) {
	type LiteBlock struct {
		Transactions     []ecommon.Hash  `json:"transactions"`
		Withdrawals      []*Withdrawal   `json:"withdrawals,omitempty"`
		Hash             ecommon.Hash    `json:"hash"`
		ParentHash       ecommon.Hash    `json:"parentHash"`
		UncleHash        ecommon.Hash    `json:"sha3Uncles"`
		Coinbase         ecommon.Address `json:"miner"`
		Root             ecommon.Hash    `json:"stateRoot"`
		TxHash           ecommon.Hash    `json:"transactionsRoot"`
		ReceiptHash      ecommon.Hash    `json:"receiptsRoot"`
		Bloom            Bloom           `json:"logsBloom"`
		Difficulty       *hexutil.Big    `json:"difficulty"`
		Number           *hexutil.Big    `json:"number"`
		GasLimit         hexutil.Uint64  `json:"gasLimit"`
		GasUsed          hexutil.Uint64  `json:"gasUsed"`
		Time             hexutil.Uint64  `json:"timestamp"`
		Extra            hexutil.Bytes   `json:"extraData"`
		MixDigest        ecommon.Hash    `json:"mixHash"`
		Nonce            BlockNonce      `json:"nonce"`
		BaseFee          *hexutil.Big    `json:"baseFeePerGas" rlp:"optional"`
		WithdrawalsHash  *ecommon.Hash   `json:"withdrawalsRoot" rlp:"optional"`
		BlobGasUsed      *hexutil.Uint64 `json:"blobGasUsed" rlp:"optional"`
		ExcessBlobGas    *hexutil.Uint64 `json:"excessBlobGas" rlp:"optional"`
		ParentBeaconRoot *ecommon.Hash   `json:"parentBeaconBlockRoot" rlp:"optional"`
		RequestsHash     *ecommon.Hash   `json:"requestsHash" rlp:"optional"`
		TotalDifficulty  *hexutil.Big    `json:"totalDifficulty"`
		Size             hexutil.Uint64  `json:"size"`
		L1Number         *hexutil.Big    `json:"l1BlockNumber,omitempty"`
		SendCount        *hexutil.Big    `json:"sendCount,omitempty"`
		SendRoot         *ecommon.Hash   `json:"sendRoot,omitempty"`
	}
	var enc LiteBlock
	enc.Transactions = l.Transactions
	enc.Withdrawals = l.Withdrawals
	enc.Hash = l.Hash
	enc.ParentHash = l.ParentHash
	enc.UncleHash = l.UncleHash
	enc.Coinbase = l.Coinbase
	enc.Root = l.Root
	enc.TxHash = l.TxHash
	enc.ReceiptHash = l.ReceiptHash
	enc.Bloom = l.Bloom
	enc.Difficulty = (*hexutil.Big)(l.Difficulty)
	enc.Number = (*hexutil.Big)(l.Number)
	enc.GasLimit = hexutil.Uint64(l.GasLimit)
	enc.GasUsed = hexutil.Uint64(l.GasUsed)
	enc.Time = hexutil.Uint64(l.Time)
	enc.Extra = l.Extra
	enc.MixDigest = l.MixDigest
	enc.Nonce = l.Nonce
	enc.BaseFee = (*hexutil.Big)(l.BaseFee)
	enc.WithdrawalsHash = l.WithdrawalsHash
	enc.BlobGasUsed = (*hexutil.Uint64)(l.BlobGasUsed)
	enc.ExcessBlobGas = (*hexutil.Uint64)(l.ExcessBlobGas)
	enc.ParentBeaconRoot = l.ParentBeaconRoot
	enc.RequestsHash = l.RequestsHash
	enc.TotalDifficulty = (*hexutil.Big)(l.TotalDifficulty)
	enc.Size = hexutil.Uint64(l.Size)
	enc.L1Number = (*hexutil.Big)(l.L1Number)
	enc.SendCount = (*hexutil.Big)(l.SendCount)
	enc.SendRoot = l.SendRoot
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (l *LiteBlock) UnmarshalJSON(input []byte) error {
	type LiteBlock struct {
		Transactions     []ecommon.Hash   `json:"transactions"`
		Withdrawals      []*Withdrawal    `json:"withdrawals,omitempty"`
		Hash             *ecommon.Hash    `json:"hash"`
		ParentHash       *ecommon.Hash    `json:"parentHash"`
		UncleHash        *ecommon.Hash    `json:"sha3Uncles"`
		Coinbase         *ecommon.Address `json:"miner"`
		Root             *ecommon.Hash    `json:"stateRoot"`
		TxHash           *ecommon.Hash    `json:"transactionsRoot"`
		ReceiptHash      *ecommon.Hash    `json:"receiptsRoot"`
		Bloom            *Bloom           `json:"logsBloom"`
		Difficulty       *hexutil.Big     `json:"difficulty"`
		Number           *hexutil.Big     `json:"number"`
		GasLimit         *hexutil.Uint64  `json:"gasLimit"`
		GasUsed          *hexutil.Uint64  `json:"gasUsed"`
		Time             *hexutil.Uint64  `json:"timestamp"`
		Extra            *hexutil.Bytes   `json:"extraData"`
		MixDigest        *ecommon.Hash    `json:"mixHash"`
		Nonce            *BlockNonce      `json:"nonce"`
		BaseFee          *hexutil.Big     `json:"baseFeePerGas" rlp:"optional"`
		WithdrawalsHash  *ecommon.Hash    `json:"withdrawalsRoot" rlp:"optional"`
		BlobGasUsed      *hexutil.Uint64  `json:"blobGasUsed" rlp:"optional"`
		ExcessBlobGas    *hexutil.Uint64  `json:"excessBlobGas" rlp:"optional"`
		ParentBeaconRoot *ecommon.Hash    `json:"parentBeaconBlockRoot" rlp:"optional"`
		RequestsHash     *ecommon.Hash    `json:"requestsHash" rlp:"optional"`
		TotalDifficulty  *hexutil.Big     `json:"totalDifficulty"`
		Size             *hexutil.Uint64  `json:"size"`
		L1Number         *hexutil.Big     `json:"l1BlockNumber,omitempty"`
		SendCount        *hexutil.Big     `json:"sendCount,omitempty"`
		SendRoot         *ecommon.Hash    `json:"sendRoot,omitempty"`
	}
	var dec LiteBlock
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.Transactions != nil {
		l.Transactions = dec.Transactions
	}
	if dec.Withdrawals != nil {
		l.Withdrawals = dec.Withdrawals
	}
	if dec.Hash != nil {
		l.Hash = *dec.Hash
	}
	if dec.ParentHash != nil {
		l.ParentHash = *dec.ParentHash
	}
	if dec.UncleHash != nil {
		l.UncleHash = *dec.UncleHash
	}
	if dec.Coinbase != nil {
		l.Coinbase = *dec.Coinbase
	}
	if dec.Root != nil {
		l.Root = *dec.Root
	}
	if dec.TxHash != nil {
		l.TxHash = *dec.TxHash
	}
	if dec.ReceiptHash != nil {
		l.ReceiptHash = *dec.ReceiptHash
	}
	if dec.Bloom != nil {
		l.Bloom = *dec.Bloom
	}
	if dec.Difficulty != nil {
		l.Difficulty = (*big.Int)(dec.Difficulty)
	}
	if dec.Number != nil {
		l.Number = (*big.Int)(dec.Number)
	}
	if dec.GasLimit != nil {
		l.GasLimit = uint64(*dec.GasLimit)
	}
	if dec.GasUsed != nil {
		l.GasUsed = uint64(*dec.GasUsed)
	}
	if dec.Time != nil {
		l.Time = uint64(*dec.Time)
	}
	if dec.Extra != nil {
		l.Extra = *dec.Extra
	}
	if dec.MixDigest != nil {
		l.MixDigest = *dec.MixDigest
	}
	if dec.Nonce != nil {
		l.Nonce = *dec.Nonce
	}
	if dec.BaseFee != nil {
		l.BaseFee = (*big.Int)(dec.BaseFee)
	}
	if dec.WithdrawalsHash != nil {
		l.WithdrawalsHash = dec.WithdrawalsHash
	}
	if dec.BlobGasUsed != nil {
		l.BlobGasUsed = (*uint64)(dec.BlobGasUsed)
	}
	if dec.ExcessBlobGas != nil {
		l.ExcessBlobGas = (*uint64)(dec.ExcessBlobGas)
	}
	if dec.ParentBeaconRoot != nil {
		l.ParentBeaconRoot = dec.ParentBeaconRoot
	}
	if dec.RequestsHash != nil {
		l.RequestsHash = dec.RequestsHash
	}
	if dec.TotalDifficulty != nil {
		l.TotalDifficulty = (*big.Int)(dec.TotalDifficulty)
	}
	if dec.Size != nil {
		l.Size = uint64(*dec.Size)
	}
	if dec.L1Number != nil {
		l.L1Number = (*big.Int)(dec.L1Number)
	}
	if dec.SendCount != nil {
		l.SendCount = (*big.Int)(dec.SendCount)
	}
	if dec.SendRoot != nil {
		l.SendRoot = dec.SendRoot
	}
	return nil
}
