// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package ethtype

import (
	"encoding/json"
	"math/big"

	"github.com/donutnomad/eths/ecommon"
	"github.com/donutnomad/eths/hexutil"
)

var _ = (*headerMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (b Block) MarshalJSON() ([]byte, error) {
	type Block struct {
		Transactions     []*Transaction  `json:"transactions"`
		Withdrawals      []*Withdrawal   `json:"withdrawals,omitempty"`
		Hash             ecommon.Hash    `json:"hash"`
		ParentHash       ecommon.Hash    `json:"parentHash"`
		UncleHash        ecommon.Hash    `json:"sha3Uncles"`
		Coinbase         ecommon.Address `json:"miner"`
		Root             ecommon.Hash    `json:"stateRoot"`
		TxHash           ecommon.Hash    `json:"transactionsRoot"`
		ReceiptHash      ecommon.Hash    `json:"receiptsRoot"`
		Bloom            Bloom           `json:"logsBloom"`
		Difficulty       *hexutil.Big    `json:"difficulty"`
		Number           *hexutil.Big    `json:"number"`
		GasLimit         hexutil.Uint64  `json:"gasLimit"`
		GasUsed          hexutil.Uint64  `json:"gasUsed"`
		Time             hexutil.Uint64  `json:"timestamp"`
		Extra            hexutil.Bytes   `json:"extraData"`
		MixDigest        ecommon.Hash    `json:"mixHash"`
		Nonce            BlockNonce      `json:"nonce"`
		BaseFee          *hexutil.Big    `json:"baseFeePerGas" rlp:"optional"`
		WithdrawalsHash  *ecommon.Hash   `json:"withdrawalsRoot" rlp:"optional"`
		BlobGasUsed      *hexutil.Uint64 `json:"blobGasUsed" rlp:"optional"`
		ExcessBlobGas    *hexutil.Uint64 `json:"excessBlobGas" rlp:"optional"`
		ParentBeaconRoot *ecommon.Hash   `json:"parentBeaconBlockRoot" rlp:"optional"`
		RequestsHash     *ecommon.Hash   `json:"requestsHash" rlp:"optional"`
		TotalDifficulty  *hexutil.Big    `json:"totalDifficulty"`
		Size             hexutil.Uint64  `json:"size"`
		L1Number         *hexutil.Big    `json:"l1BlockNumber,omitempty"`
		SendCount        *hexutil.Big    `json:"sendCount,omitempty"`
		SendRoot         *ecommon.Hash   `json:"sendRoot,omitempty"`
	}
	var enc Block
	enc.Transactions = b.Transactions
	enc.Withdrawals = b.Withdrawals
	enc.Hash = b.Hash
	enc.ParentHash = b.ParentHash
	enc.UncleHash = b.UncleHash
	enc.Coinbase = b.Coinbase
	enc.Root = b.Root
	enc.TxHash = b.TxHash
	enc.ReceiptHash = b.ReceiptHash
	enc.Bloom = b.Bloom
	enc.Difficulty = (*hexutil.Big)(b.Difficulty)
	enc.Number = (*hexutil.Big)(b.Number)
	enc.GasLimit = hexutil.Uint64(b.GasLimit)
	enc.GasUsed = hexutil.Uint64(b.GasUsed)
	enc.Time = hexutil.Uint64(b.Time)
	enc.Extra = b.Extra
	enc.MixDigest = b.MixDigest
	enc.Nonce = b.Nonce
	enc.BaseFee = (*hexutil.Big)(b.BaseFee)
	enc.WithdrawalsHash = b.WithdrawalsHash
	enc.BlobGasUsed = (*hexutil.Uint64)(b.BlobGasUsed)
	enc.ExcessBlobGas = (*hexutil.Uint64)(b.ExcessBlobGas)
	enc.ParentBeaconRoot = b.ParentBeaconRoot
	enc.RequestsHash = b.RequestsHash
	enc.TotalDifficulty = (*hexutil.Big)(b.TotalDifficulty)
	enc.Size = hexutil.Uint64(b.Size)
	enc.L1Number = (*hexutil.Big)(b.L1Number)
	enc.SendCount = (*hexutil.Big)(b.SendCount)
	enc.SendRoot = b.SendRoot
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (b *Block) UnmarshalJSON(input []byte) error {
	type Block struct {
		Transactions     []*Transaction   `json:"transactions"`
		Withdrawals      []*Withdrawal    `json:"withdrawals,omitempty"`
		Hash             *ecommon.Hash    `json:"hash"`
		ParentHash       *ecommon.Hash    `json:"parentHash"`
		UncleHash        *ecommon.Hash    `json:"sha3Uncles"`
		Coinbase         *ecommon.Address `json:"miner"`
		Root             *ecommon.Hash    `json:"stateRoot"`
		TxHash           *ecommon.Hash    `json:"transactionsRoot"`
		ReceiptHash      *ecommon.Hash    `json:"receiptsRoot"`
		Bloom            *Bloom           `json:"logsBloom"`
		Difficulty       *hexutil.Big     `json:"difficulty"`
		Number           *hexutil.Big     `json:"number"`
		GasLimit         *hexutil.Uint64  `json:"gasLimit"`
		GasUsed          *hexutil.Uint64  `json:"gasUsed"`
		Time             *hexutil.Uint64  `json:"timestamp"`
		Extra            *hexutil.Bytes   `json:"extraData"`
		MixDigest        *ecommon.Hash    `json:"mixHash"`
		Nonce            *BlockNonce      `json:"nonce"`
		BaseFee          *hexutil.Big     `json:"baseFeePerGas" rlp:"optional"`
		WithdrawalsHash  *ecommon.Hash    `json:"withdrawalsRoot" rlp:"optional"`
		BlobGasUsed      *hexutil.Uint64  `json:"blobGasUsed" rlp:"optional"`
		ExcessBlobGas    *hexutil.Uint64  `json:"excessBlobGas" rlp:"optional"`
		ParentBeaconRoot *ecommon.Hash    `json:"parentBeaconBlockRoot" rlp:"optional"`
		RequestsHash     *ecommon.Hash    `json:"requestsHash" rlp:"optional"`
		TotalDifficulty  *hexutil.Big     `json:"totalDifficulty"`
		Size             *hexutil.Uint64  `json:"size"`
		L1Number         *hexutil.Big     `json:"l1BlockNumber,omitempty"`
		SendCount        *hexutil.Big     `json:"sendCount,omitempty"`
		SendRoot         *ecommon.Hash    `json:"sendRoot,omitempty"`
	}
	var dec Block
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.Transactions != nil {
		b.Transactions = dec.Transactions
	}
	if dec.Withdrawals != nil {
		b.Withdrawals = dec.Withdrawals
	}
	if dec.Hash != nil {
		b.Hash = *dec.Hash
	}
	if dec.ParentHash != nil {
		b.ParentHash = *dec.ParentHash
	}
	if dec.UncleHash != nil {
		b.UncleHash = *dec.UncleHash
	}
	if dec.Coinbase != nil {
		b.Coinbase = *dec.Coinbase
	}
	if dec.Root != nil {
		b.Root = *dec.Root
	}
	if dec.TxHash != nil {
		b.TxHash = *dec.TxHash
	}
	if dec.ReceiptHash != nil {
		b.ReceiptHash = *dec.ReceiptHash
	}
	if dec.Bloom != nil {
		b.Bloom = *dec.Bloom
	}
	if dec.Difficulty != nil {
		b.Difficulty = (*big.Int)(dec.Difficulty)
	}
	if dec.Number != nil {
		b.Number = (*big.Int)(dec.Number)
	}
	if dec.GasLimit != nil {
		b.GasLimit = uint64(*dec.GasLimit)
	}
	if dec.GasUsed != nil {
		b.GasUsed = uint64(*dec.GasUsed)
	}
	if dec.Time != nil {
		b.Time = uint64(*dec.Time)
	}
	if dec.Extra != nil {
		b.Extra = *dec.Extra
	}
	if dec.MixDigest != nil {
		b.MixDigest = *dec.MixDigest
	}
	if dec.Nonce != nil {
		b.Nonce = *dec.Nonce
	}
	if dec.BaseFee != nil {
		b.BaseFee = (*big.Int)(dec.BaseFee)
	}
	if dec.WithdrawalsHash != nil {
		b.WithdrawalsHash = dec.WithdrawalsHash
	}
	if dec.BlobGasUsed != nil {
		b.BlobGasUsed = (*uint64)(dec.BlobGasUsed)
	}
	if dec.ExcessBlobGas != nil {
		b.ExcessBlobGas = (*uint64)(dec.ExcessBlobGas)
	}
	if dec.ParentBeaconRoot != nil {
		b.ParentBeaconRoot = dec.ParentBeaconRoot
	}
	if dec.RequestsHash != nil {
		b.RequestsHash = dec.RequestsHash
	}
	if dec.TotalDifficulty != nil {
		b.TotalDifficulty = (*big.Int)(dec.TotalDifficulty)
	}
	if dec.Size != nil {
		b.Size = uint64(*dec.Size)
	}
	if dec.L1Number != nil {
		b.L1Number = (*big.Int)(dec.L1Number)
	}
	if dec.SendCount != nil {
		b.SendCount = (*big.Int)(dec.SendCount)
	}
	if dec.SendRoot != nil {
		b.SendRoot = dec.SendRoot
	}
	return nil
}
