package ethtype

import (
	"github.com/donutnomad/eths/ecommon"
	"github.com/donutnomad/eths/hexutil"
)

// Log represents a contract log event. These events are generated by the LOG opcode and
// stored/indexed by the node.
type Log struct {
	// Consensus fields:
	// address of the contract that generated the event
	Address ecommon.Address `json:"address"`
	// list of topics provided by the contract.
	Topics []ecommon.Hash `json:"topics"`
	// supplied by the contract, usually ABI-encoded
	Data []byte `json:"data"`

	// Derived fields. These fields are filled in by the node
	// but not secured by consensus.
	// block in which the transaction was included
	BlockNumber uint64 `json:"blockNumber" rlp:"-"`
	// hash of the transaction
	TxHash ecommon.Hash `json:"transactionHash" rlp:"-"`
	// index of the transaction in the block
	TxIndex uint `json:"transactionIndex" rlp:"-"`
	// hash of the block in which the transaction was included
	BlockHash ecommon.Hash `json:"blockHash" rlp:"-"`
	// timestamp of the block in which the transaction was included
	BlockTimestamp uint64 `json:"blockTimestamp" rlp:"-"`
	// index of the log in the block
	Index uint `json:"logIndex" rlp:"-"`

	// The Removed field is true if this log was reverted due to a chain reorganisation.
	// You must pay attention to this field if you receive logs through a filter query.
	Removed bool `json:"removed" rlp:"-"`
}

type logMarshaling struct {
	Data           hexutil.Bytes
	BlockNumber    hexutil.Uint64
	TxIndex        hexutil.Uint
	BlockTimestamp hexutil.Uint64
	Index          hexutil.Uint
}
