// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package ethtype

import (
	"encoding/json"
	"errors"
	"math/big"

	"github.com/donutnomad/eths/ecommon"
	"github.com/ethereum/go-ethereum/common/hexutil"
)

var _ = (*receiptMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (t TxReceipt) MarshalJSON() ([]byte, error) {
	type TxReceipt struct {
		Type              hexutil.Uint64   `json:"type,omitempty"`
		PostState         hexutil.Bytes    `json:"root"`
		Status            hexutil.Uint64   `json:"status"`
		CumulativeGasUsed hexutil.Uint64   `json:"cumulativeGasUsed" gencodec:"required"`
		Bloom             Bloom            `json:"logsBloom"         gencodec:"required"`
		Logs              []*Log           `json:"logs"              gencodec:"required"`
		TxHash            ecommon.Hash     `json:"transactionHash" gencodec:"required"`
		ContractAddress   *ecommon.Address `json:"contractAddress"`
		From              ecommon.Address  `json:"from"`
		To                *ecommon.Address `json:"to"`
		GasUsed           hexutil.Uint64   `json:"gasUsed" gencodec:"required"`
		EffectiveGasPrice *hexutil.Big     `json:"effectiveGasPrice"`
		BlobGasUsed       hexutil.Uint64   `json:"blobGasUsed,omitempty"`
		BlobGasPrice      *hexutil.Big     `json:"blobGasPrice,omitempty"`
		BlockHash         ecommon.Hash     `json:"blockHash,omitempty"`
		BlockNumber       *hexutil.Big     `json:"blockNumber,omitempty"`
		TransactionIndex  hexutil.Uint     `json:"transactionIndex"`
	}
	var enc TxReceipt
	enc.Type = hexutil.Uint64(t.Type)
	enc.PostState = t.PostState
	enc.Status = hexutil.Uint64(t.Status)
	enc.CumulativeGasUsed = hexutil.Uint64(t.CumulativeGasUsed)
	enc.Bloom = t.Bloom
	enc.Logs = t.Logs
	enc.TxHash = t.TxHash
	enc.ContractAddress = t.ContractAddress
	enc.From = t.From
	enc.To = t.To
	enc.GasUsed = hexutil.Uint64(t.GasUsed)
	enc.EffectiveGasPrice = (*hexutil.Big)(t.EffectiveGasPrice)
	enc.BlobGasUsed = hexutil.Uint64(t.BlobGasUsed)
	enc.BlobGasPrice = (*hexutil.Big)(t.BlobGasPrice)
	enc.BlockHash = t.BlockHash
	enc.BlockNumber = (*hexutil.Big)(t.BlockNumber)
	enc.TransactionIndex = hexutil.Uint(t.TransactionIndex)
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (t *TxReceipt) UnmarshalJSON(input []byte) error {
	type TxReceipt struct {
		Type              *hexutil.Uint64  `json:"type,omitempty"`
		PostState         *hexutil.Bytes   `json:"root"`
		Status            *hexutil.Uint64  `json:"status"`
		CumulativeGasUsed *hexutil.Uint64  `json:"cumulativeGasUsed" gencodec:"required"`
		Bloom             *Bloom           `json:"logsBloom"         gencodec:"required"`
		Logs              []*Log           `json:"logs"              gencodec:"required"`
		TxHash            *ecommon.Hash    `json:"transactionHash" gencodec:"required"`
		ContractAddress   *ecommon.Address `json:"contractAddress"`
		From              *ecommon.Address `json:"from"`
		To                *ecommon.Address `json:"to"`
		GasUsed           *hexutil.Uint64  `json:"gasUsed" gencodec:"required"`
		EffectiveGasPrice *hexutil.Big     `json:"effectiveGasPrice"`
		BlobGasUsed       *hexutil.Uint64  `json:"blobGasUsed,omitempty"`
		BlobGasPrice      *hexutil.Big     `json:"blobGasPrice,omitempty"`
		BlockHash         *ecommon.Hash    `json:"blockHash,omitempty"`
		BlockNumber       *hexutil.Big     `json:"blockNumber,omitempty"`
		TransactionIndex  *hexutil.Uint    `json:"transactionIndex"`
	}
	var dec TxReceipt
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.Type != nil {
		t.Type = uint8(*dec.Type)
	}
	if dec.PostState != nil {
		t.PostState = *dec.PostState
	}
	if dec.Status != nil {
		t.Status = uint64(*dec.Status)
	}
	if dec.CumulativeGasUsed == nil {
		return errors.New("missing required field 'cumulativeGasUsed' for TxReceipt")
	}
	t.CumulativeGasUsed = uint64(*dec.CumulativeGasUsed)
	if dec.Bloom == nil {
		return errors.New("missing required field 'logsBloom' for TxReceipt")
	}
	t.Bloom = *dec.Bloom
	if dec.Logs == nil {
		return errors.New("missing required field 'logs' for TxReceipt")
	}
	t.Logs = dec.Logs
	if dec.TxHash == nil {
		return errors.New("missing required field 'transactionHash' for TxReceipt")
	}
	t.TxHash = *dec.TxHash
	if dec.ContractAddress != nil {
		t.ContractAddress = dec.ContractAddress
	}
	if dec.From != nil {
		t.From = *dec.From
	}
	if dec.To != nil {
		t.To = dec.To
	}
	if dec.GasUsed == nil {
		return errors.New("missing required field 'gasUsed' for TxReceipt")
	}
	t.GasUsed = uint64(*dec.GasUsed)
	if dec.EffectiveGasPrice != nil {
		t.EffectiveGasPrice = (*big.Int)(dec.EffectiveGasPrice)
	}
	if dec.BlobGasUsed != nil {
		t.BlobGasUsed = uint64(*dec.BlobGasUsed)
	}
	if dec.BlobGasPrice != nil {
		t.BlobGasPrice = (*big.Int)(dec.BlobGasPrice)
	}
	if dec.BlockHash != nil {
		t.BlockHash = *dec.BlockHash
	}
	if dec.BlockNumber != nil {
		t.BlockNumber = (*big.Int)(dec.BlockNumber)
	}
	if dec.TransactionIndex != nil {
		t.TransactionIndex = uint(*dec.TransactionIndex)
	}
	return nil
}
