// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package ethtype

import (
	"encoding/json"
	"math/big"

	"github.com/donutnomad/eths/ecommon"
	"github.com/donutnomad/eths/hexutil"
)

var _ = (*txMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (t Tx) MarshalJSON() ([]byte, error) {
	type Tx struct {
		Type                 hexutil.Uint64         `json:"type"`
		ChainID              *hexutil.Big           `json:"chainId,omitempty"`
		Nonce                hexutil.Uint64         `json:"nonce"`
		From                 ecommon.Address        `json:"from"`
		To                   *ecommon.Address       `json:"to"`
		Gas                  hexutil.Uint64         `json:"gas"`
		GasPrice             *hexutil.Big           `json:"gasPrice"`
		MaxPriorityFeePerGas *hexutil.Big           `json:"maxPriorityFeePerGas"`
		MaxFeePerGas         *hexutil.Big           `json:"maxFeePerGas"`
		MaxFeePerBlobGas     *hexutil.Big           `json:"maxFeePerBlobGas,omitempty"`
		Value                *hexutil.Big           `json:"value"`
		Input                hexutil.Bytes          `json:"input"`
		AccessList           AccessList             `json:"accessList,omitempty"`
		BlobVersionedHashes  []ecommon.Hash         `json:"blobVersionedHashes,omitempty"`
		AuthorizationList    []SetCodeAuthorization `json:"authorizationList,omitempty"`
		V                    *hexutil.Big           `json:"v"`
		R                    *hexutil.Big           `json:"r"`
		S                    *hexutil.Big           `json:"s"`
		YParity              hexutil.Uint64         `json:"yParity,omitempty"`
		Hash                 ecommon.Hash           `json:"hash"`
	}
	var enc Tx
	enc.Type = hexutil.Uint64(t.Type)
	enc.ChainID = (*hexutil.Big)(t.ChainID)
	enc.Nonce = hexutil.Uint64(t.Nonce)
	enc.From = t.From
	enc.To = t.To
	enc.Gas = hexutil.Uint64(t.Gas)
	enc.GasPrice = (*hexutil.Big)(t.GasPrice)
	enc.MaxPriorityFeePerGas = (*hexutil.Big)(t.MaxPriorityFeePerGas)
	enc.MaxFeePerGas = (*hexutil.Big)(t.MaxFeePerGas)
	enc.MaxFeePerBlobGas = (*hexutil.Big)(t.MaxFeePerBlobGas)
	enc.Value = (*hexutil.Big)(t.Value)
	enc.Input = t.Input
	enc.AccessList = t.AccessList
	enc.BlobVersionedHashes = t.BlobVersionedHashes
	enc.AuthorizationList = t.AuthorizationList
	enc.V = (*hexutil.Big)(t.V)
	enc.R = (*hexutil.Big)(t.R)
	enc.S = (*hexutil.Big)(t.S)
	enc.YParity = hexutil.Uint64(t.YParity)
	enc.Hash = t.Hash
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (t *Tx) UnmarshalJSON(input []byte) error {
	type Tx struct {
		Type                 *hexutil.Uint64        `json:"type"`
		ChainID              *hexutil.Big           `json:"chainId,omitempty"`
		Nonce                *hexutil.Uint64        `json:"nonce"`
		From                 *ecommon.Address       `json:"from"`
		To                   *ecommon.Address       `json:"to"`
		Gas                  *hexutil.Uint64        `json:"gas"`
		GasPrice             *hexutil.Big           `json:"gasPrice"`
		MaxPriorityFeePerGas *hexutil.Big           `json:"maxPriorityFeePerGas"`
		MaxFeePerGas         *hexutil.Big           `json:"maxFeePerGas"`
		MaxFeePerBlobGas     *hexutil.Big           `json:"maxFeePerBlobGas,omitempty"`
		Value                *hexutil.Big           `json:"value"`
		Input                *hexutil.Bytes         `json:"input"`
		AccessList           *AccessList            `json:"accessList,omitempty"`
		BlobVersionedHashes  []ecommon.Hash         `json:"blobVersionedHashes,omitempty"`
		AuthorizationList    []SetCodeAuthorization `json:"authorizationList,omitempty"`
		V                    *hexutil.Big           `json:"v"`
		R                    *hexutil.Big           `json:"r"`
		S                    *hexutil.Big           `json:"s"`
		YParity              *hexutil.Uint64        `json:"yParity,omitempty"`
		Hash                 *ecommon.Hash          `json:"hash"`
	}
	var dec Tx
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.Type != nil {
		t.Type = uint8(*dec.Type)
	}
	if dec.ChainID != nil {
		t.ChainID = (*big.Int)(dec.ChainID)
	}
	if dec.Nonce != nil {
		t.Nonce = uint64(*dec.Nonce)
	}
	if dec.From != nil {
		t.From = *dec.From
	}
	if dec.To != nil {
		t.To = dec.To
	}
	if dec.Gas != nil {
		t.Gas = uint64(*dec.Gas)
	}
	if dec.GasPrice != nil {
		t.GasPrice = (*big.Int)(dec.GasPrice)
	}
	if dec.MaxPriorityFeePerGas != nil {
		t.MaxPriorityFeePerGas = (*big.Int)(dec.MaxPriorityFeePerGas)
	}
	if dec.MaxFeePerGas != nil {
		t.MaxFeePerGas = (*big.Int)(dec.MaxFeePerGas)
	}
	if dec.MaxFeePerBlobGas != nil {
		t.MaxFeePerBlobGas = (*big.Int)(dec.MaxFeePerBlobGas)
	}
	if dec.Value != nil {
		t.Value = (*big.Int)(dec.Value)
	}
	if dec.Input != nil {
		t.Input = *dec.Input
	}
	if dec.AccessList != nil {
		t.AccessList = *dec.AccessList
	}
	if dec.BlobVersionedHashes != nil {
		t.BlobVersionedHashes = dec.BlobVersionedHashes
	}
	if dec.AuthorizationList != nil {
		t.AuthorizationList = dec.AuthorizationList
	}
	if dec.V != nil {
		t.V = (*big.Int)(dec.V)
	}
	if dec.R != nil {
		t.R = (*big.Int)(dec.R)
	}
	if dec.S != nil {
		t.S = (*big.Int)(dec.S)
	}
	if dec.YParity != nil {
		t.YParity = uint64(*dec.YParity)
	}
	if dec.Hash != nil {
		t.Hash = *dec.Hash
	}
	return nil
}
