// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package ethtype

import (
	"encoding/json"
	"errors"
	"math/big"

	"github.com/donutnomad/eths/ecommon"
	"github.com/ethereum/go-ethereum/common/hexutil"
	"github.com/ethereum/go-ethereum/crypto/kzg4844"
)

var _ = (*txMarshaling)(nil)
var _ = (*receiptMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (t TxDetail) MarshalJSON() ([]byte, error) {
	type TxDetail struct {
		Type                 hexutil.Uint64         `json:"type"`
		ChainID              *hexutil.Big           `json:"chainId,omitempty"`
		Nonce                hexutil.Uint64         `json:"nonce"`
		From                 ecommon.Address        `json:"from"`
		To                   *ecommon.Address       `json:"to"`
		Gas                  hexutil.Uint64         `json:"gas"`
		GasPrice             *hexutil.Big           `json:"gasPrice"`
		MaxPriorityFeePerGas *hexutil.Big           `json:"maxPriorityFeePerGas"`
		MaxFeePerGas         *hexutil.Big           `json:"maxFeePerGas"`
		MaxFeePerBlobGas     *hexutil.Big           `json:"maxFeePerBlobGas,omitempty"`
		Value                *hexutil.Big           `json:"value"`
		Input                hexutil.Bytes          `json:"input"`
		BlobVersionedHashes  []ecommon.Hash         `json:"blobVersionedHashes,omitempty"`
		AuthorizationList    []SetCodeAuthorization `json:"authorizationList,omitempty"`
		V                    *hexutil.Big           `json:"v"`
		R                    *hexutil.Big           `json:"r"`
		S                    *hexutil.Big           `json:"s"`
		YParity              hexutil.Uint64         `json:"yParity,omitempty"`
		Blobs                []kzg4844.Blob         `json:"blobs,omitempty"`
		Commitments          []kzg4844.Commitment   `json:"commitments,omitempty"`
		Proofs               []kzg4844.Proof        `json:"proofs,omitempty"`
		Hash                 ecommon.Hash           `json:"hash"`
		PostState            hexutil.Bytes          `json:"root"`
		Status               hexutil.Uint64         `json:"status"`
		CumulativeGasUsed    hexutil.Uint64         `json:"cumulativeGasUsed" gencodec:"required"`
		Bloom                Bloom                  `json:"logsBloom"         gencodec:"required"`
		Logs                 []*Log                 `json:"logs"              gencodec:"required"`
		TxHash               ecommon.Hash           `json:"transactionHash" gencodec:"required"`
		ContractAddress      *ecommon.Address       `json:"contractAddress"`
		GasUsed              hexutil.Uint64         `json:"gasUsed" gencodec:"required"`
		EffectiveGasPrice    *hexutil.Big           `json:"effectiveGasPrice"`
		BlobGasUsed          hexutil.Uint64         `json:"blobGasUsed,omitempty"`
		BlobGasPrice         *hexutil.Big           `json:"blobGasPrice,omitempty"`
		BlockHash            ecommon.Hash           `json:"blockHash,omitempty"`
		BlockNumber          *hexutil.Big           `json:"blockNumber,omitempty"`
		TransactionIndex     hexutil.Uint           `json:"transactionIndex"`
	}
	var enc TxDetail
	enc.Type = hexutil.Uint64(t.Tx.Type)
	enc.ChainID = (*hexutil.Big)(t.ChainID)
	enc.Nonce = hexutil.Uint64(t.Nonce)
	enc.From = t.Tx.From
	enc.To = t.Tx.To
	enc.Gas = hexutil.Uint64(t.Gas)
	enc.GasPrice = (*hexutil.Big)(t.GasPrice)
	enc.MaxPriorityFeePerGas = (*hexutil.Big)(t.MaxPriorityFeePerGas)
	enc.MaxFeePerGas = (*hexutil.Big)(t.MaxFeePerGas)
	enc.MaxFeePerBlobGas = (*hexutil.Big)(t.MaxFeePerBlobGas)
	enc.Value = (*hexutil.Big)(t.Value)
	enc.Input = t.Input
	enc.BlobVersionedHashes = t.BlobVersionedHashes
	enc.AuthorizationList = t.AuthorizationList
	enc.V = (*hexutil.Big)(t.V)
	enc.R = (*hexutil.Big)(t.R)
	enc.S = (*hexutil.Big)(t.S)
	enc.YParity = hexutil.Uint64(t.YParity)
	enc.Blobs = t.Blobs
	enc.Commitments = t.Commitments
	enc.Proofs = t.Proofs
	enc.Hash = t.Hash
	enc.PostState = t.PostState
	enc.Status = hexutil.Uint64(t.Status)
	enc.CumulativeGasUsed = hexutil.Uint64(t.CumulativeGasUsed)
	enc.Bloom = t.Bloom
	enc.Logs = t.Logs
	enc.TxHash = t.TxHash
	enc.ContractAddress = t.ContractAddress
	enc.GasUsed = hexutil.Uint64(t.GasUsed)
	enc.EffectiveGasPrice = (*hexutil.Big)(t.EffectiveGasPrice)
	enc.BlobGasUsed = hexutil.Uint64(t.BlobGasUsed)
	enc.BlobGasPrice = (*hexutil.Big)(t.BlobGasPrice)
	enc.BlockHash = t.BlockHash
	enc.BlockNumber = (*hexutil.Big)(t.BlockNumber)
	enc.TransactionIndex = hexutil.Uint(t.TransactionIndex)
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (t *TxDetail) UnmarshalJSON(input []byte) error {
	type TxDetail struct {
		Type                 *hexutil.Uint64        `json:"type"`
		ChainID              *hexutil.Big           `json:"chainId,omitempty"`
		Nonce                *hexutil.Uint64        `json:"nonce"`
		From                 *ecommon.Address       `json:"from"`
		To                   *ecommon.Address       `json:"to"`
		Gas                  *hexutil.Uint64        `json:"gas"`
		GasPrice             *hexutil.Big           `json:"gasPrice"`
		MaxPriorityFeePerGas *hexutil.Big           `json:"maxPriorityFeePerGas"`
		MaxFeePerGas         *hexutil.Big           `json:"maxFeePerGas"`
		MaxFeePerBlobGas     *hexutil.Big           `json:"maxFeePerBlobGas,omitempty"`
		Value                *hexutil.Big           `json:"value"`
		Input                *hexutil.Bytes         `json:"input"`
		BlobVersionedHashes  []ecommon.Hash         `json:"blobVersionedHashes,omitempty"`
		AuthorizationList    []SetCodeAuthorization `json:"authorizationList,omitempty"`
		V                    *hexutil.Big           `json:"v"`
		R                    *hexutil.Big           `json:"r"`
		S                    *hexutil.Big           `json:"s"`
		YParity              *hexutil.Uint64        `json:"yParity,omitempty"`
		Blobs                []kzg4844.Blob         `json:"blobs,omitempty"`
		Commitments          []kzg4844.Commitment   `json:"commitments,omitempty"`
		Proofs               []kzg4844.Proof        `json:"proofs,omitempty"`
		Hash                 *ecommon.Hash          `json:"hash"`
		PostState            *hexutil.Bytes         `json:"root"`
		Status               *hexutil.Uint64        `json:"status"`
		CumulativeGasUsed    *hexutil.Uint64        `json:"cumulativeGasUsed" gencodec:"required"`
		Bloom                *Bloom                 `json:"logsBloom"         gencodec:"required"`
		Logs                 []*Log                 `json:"logs"              gencodec:"required"`
		TxHash               *ecommon.Hash          `json:"transactionHash" gencodec:"required"`
		ContractAddress      *ecommon.Address       `json:"contractAddress"`
		GasUsed              *hexutil.Uint64        `json:"gasUsed" gencodec:"required"`
		EffectiveGasPrice    *hexutil.Big           `json:"effectiveGasPrice"`
		BlobGasUsed          *hexutil.Uint64        `json:"blobGasUsed,omitempty"`
		BlobGasPrice         *hexutil.Big           `json:"blobGasPrice,omitempty"`
		BlockHash            *ecommon.Hash          `json:"blockHash,omitempty"`
		BlockNumber          *hexutil.Big           `json:"blockNumber,omitempty"`
		TransactionIndex     *hexutil.Uint          `json:"transactionIndex"`
	}
	var dec TxDetail
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.Type != nil {
		t.Tx.Type = uint8(*dec.Type)
	}
	if dec.ChainID != nil {
		t.ChainID = (*big.Int)(dec.ChainID)
	}
	if dec.Nonce != nil {
		t.Nonce = uint64(*dec.Nonce)
	}
	if dec.From != nil {
		t.Tx.From = *dec.From
	}
	if dec.To != nil {
		t.Tx.To = dec.To
	}
	if dec.Gas != nil {
		t.Gas = uint64(*dec.Gas)
	}
	if dec.GasPrice != nil {
		t.GasPrice = (*big.Int)(dec.GasPrice)
	}
	if dec.MaxPriorityFeePerGas != nil {
		t.MaxPriorityFeePerGas = (*big.Int)(dec.MaxPriorityFeePerGas)
	}
	if dec.MaxFeePerGas != nil {
		t.MaxFeePerGas = (*big.Int)(dec.MaxFeePerGas)
	}
	if dec.MaxFeePerBlobGas != nil {
		t.MaxFeePerBlobGas = (*big.Int)(dec.MaxFeePerBlobGas)
	}
	if dec.Value != nil {
		t.Value = (*big.Int)(dec.Value)
	}
	if dec.Input != nil {
		t.Input = *dec.Input
	}
	if dec.BlobVersionedHashes != nil {
		t.BlobVersionedHashes = dec.BlobVersionedHashes
	}
	if dec.AuthorizationList != nil {
		t.AuthorizationList = dec.AuthorizationList
	}
	if dec.V != nil {
		t.V = (*big.Int)(dec.V)
	}
	if dec.R != nil {
		t.R = (*big.Int)(dec.R)
	}
	if dec.S != nil {
		t.S = (*big.Int)(dec.S)
	}
	if dec.YParity != nil {
		t.YParity = uint64(*dec.YParity)
	}
	if dec.Blobs != nil {
		t.Blobs = dec.Blobs
	}
	if dec.Commitments != nil {
		t.Commitments = dec.Commitments
	}
	if dec.Proofs != nil {
		t.Proofs = dec.Proofs
	}
	if dec.Hash != nil {
		t.Hash = *dec.Hash
	}
	if dec.PostState != nil {
		t.PostState = *dec.PostState
	}
	if dec.Status != nil {
		t.Status = uint64(*dec.Status)
	}
	if dec.CumulativeGasUsed == nil {
		return errors.New("missing required field 'cumulativeGasUsed' for TxDetail")
	}
	t.CumulativeGasUsed = uint64(*dec.CumulativeGasUsed)
	if dec.Bloom == nil {
		return errors.New("missing required field 'logsBloom' for TxDetail")
	}
	t.Bloom = *dec.Bloom
	if dec.Logs == nil {
		return errors.New("missing required field 'logs' for TxDetail")
	}
	t.Logs = dec.Logs
	if dec.TxHash == nil {
		return errors.New("missing required field 'transactionHash' for TxDetail")
	}
	t.TxHash = *dec.TxHash
	if dec.ContractAddress != nil {
		t.ContractAddress = dec.ContractAddress
	}
	if dec.GasUsed == nil {
		return errors.New("missing required field 'gasUsed' for TxDetail")
	}
	t.GasUsed = uint64(*dec.GasUsed)
	if dec.EffectiveGasPrice != nil {
		t.EffectiveGasPrice = (*big.Int)(dec.EffectiveGasPrice)
	}
	if dec.BlobGasUsed != nil {
		t.BlobGasUsed = uint64(*dec.BlobGasUsed)
	}
	if dec.BlobGasPrice != nil {
		t.BlobGasPrice = (*big.Int)(dec.BlobGasPrice)
	}
	if dec.BlockHash != nil {
		t.BlockHash = *dec.BlockHash
	}
	if dec.BlockNumber != nil {
		t.BlockNumber = (*big.Int)(dec.BlockNumber)
	}
	if dec.TransactionIndex != nil {
		t.TransactionIndex = uint(*dec.TransactionIndex)
	}
	return nil
}
