


build:
	 go build -o eip712gen main.go
	./eip712gen -def "SwapData(address token,address nft,uint256 nftId,uint256 amount,uint256 tokenAmount,address buyer,address seller,uint256 deadline,uint256 nonce)" -o swapdata_eip712.go